# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Format
format = '''$directory$git_branch$git_status$cmd_duration$nodejs$all$character'''

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
format = '[$path](bold #f38ba8)[$read_only]($read_only_style) '
truncation_length = 3
truncation_symbol = '../'
use_os_path_sep = false

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)](bold fg:214) '
symbol = ' '

[git_status]
style = 'bold fg:214'

[cmd_duration]
min_time = 0
format = '󱦟 [$duration](bold yellow) '

[username]
show_always = false
format = '[$user]($style)'
style_user = 'bold #74c7ec'

[character]
# success_symbol = '[\$](bold green)' # 
vicmd_symbol = "[\ue62b](white)" # 
# error_symbol = '[\$](red)' # 
